apiVersion: v2
name: warpflow-runtime
description: A helm chart for running Warpflow flows as a service
type: application
version: 0.1.1
appVersion: latest
maintainers:
  - name: Warpflow
    email: contact@warpflow.io
